import { chromium } from 'playwright';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { startServer, BROWSER_ARGS } from './server.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { server, port } = await startServer(root, async () => {});
const browser = await chromium.launch({ args: BROWSER_ARGS });
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
page.on('pageerror', (e) => console.log('[pageerror]', e.message));
await page.goto(`http://127.0.0.1:${port}/index.html`);
await page.evaluate(() => window.ready);
const out = await page.evaluate(async () => {
  const A = await import('./src/acts/act1.js');
  const C = await import('./src/acts/common.js');
  const W = await import('./src/elements/world.js');
  const CR = await import('./src/elements/crowd.js');
  const mk = () => { const c = document.createElement('canvas'); c.width = 1920; c.height = 1080; return c.getContext('2d', { alpha: false }); };
  const R = { b: mk(), g: mk(), S: 1 };
  const flush = () => { R.b.getImageData(0, 0, 1, 1); R.g.getImageData(0, 0, 1, 1); };
  const T = (name, fn) => { flush(); const a = performance.now(); fn(); flush(); return name + ':' + (performance.now() - a).toFixed(0); };
  const res = [];
  const { crowd } = C.world();
  res.push('members=' + crowd.length);
  const cam = A.eyeCam({ a: 0.4, D: 30, H: 100, f: 1150 });
  const st = (m) => ({ led: [57, 255, 20], ledI: 1 });
  res.push(T('pool', () => { W.floorPool(R, cam, 0, -9, 20, [57, 255, 20], 1); W.floorPool(R, cam, 0, -9, 40, [60, 50, 120], 0.5); }));
  res.push(T('strike', () => W.strikeLine(R, cam, -9, -70, 70, {})));
  res.push(T('crowdTop', () => CR.drawCrowdTop(R, cam, crowd, st, {})));
  res.push(T('candle', () => W.drawCandleBox(R, cam, { x: 0, z: -9, close: 3, w: 3, col: [57, 255, 20] })));
  res.push(T('hilo', () => C.hiLo(C.price1, 0, 10)));
  const cam2 = A.eyeCam({ a: 0.45, D: 32.6, H: 104, f: 1150 });
  res.push(T('drawEye', () => A.drawEye(R, cam2, 2.6, {})));
  res.push(T('crowdTop2', () => CR.drawCrowdTop(R, cam2, crowd, st, { fogCol: [16, 14, 30], fogNear: 30, fogFar: 90, keyCol: [57,255,20], keyK: 1, squash: 0.8 })));
  const st3 = (m) => { const pk = C.pickOf(m); return { led: C.ledFor(pk), ledI: pk ? 1 : 0.35 }; };
  res.push(T('crowdTop3', () => CR.drawCrowdTop(R, cam2, crowd, st3, { fogCol: [16, 14, 30], fogNear: 30, fogFar: 90, keyCol: [57,255,20], keyK: 1, squash: 0.8 })));
  res.push(T('pool2', () => { W.floorPool(R, cam2, 0, -9, 17, [57, 255, 20], 1); W.floorPool(R, cam2, 0, -9, 40, [60, 50, 120], 0.5); }));
  const F = await import('./src/film.js');
  const P = {};
  res.push(T('renderFilm2.6', () => F.renderFilm(2.6, R, P)));
  res.push(T('renderFilm3.0', () => F.renderFilm(3.0, R, P)));
  const FX = await import('./src/elements/fx.js');
  res.push(T('timer', () => FX.timerHUD(R, 12)));
  const cam4 = A.eyeCam({ a: 0.45, D: 32.6, H: 104, f: 1150 });
  const stT = (t) => (m) => { const pk = t >= C.pickTime(m) ? C.pickOf(m) : 0; const s = { led: C.ledFor(pk), ledI: pk ? 1 : 0.35 }; if (m.hero) Object.assign(s, { pearl: true, stripes: 'y', led: [57,255,20], ledI: 1.2 }); return s; };
  res.push(T('drawEyeSt', () => A.drawEye(R, cam4, 2.6, { st: stT(2.6) })));
  return res.join('  ');
});
console.log(out);
await browser.close(); server.close();
